name: StuzzTotallyLogical
version: ${project.version}
authors:
  - Nightgunner5
  - 7031

description: 'A world generator that generates totally logical worlds. Nope, nothing crazy here!'

main: com.stuzzhosting.totallylogical.Main