name: StuzzTotallyLogical
version: ${project.version}
authors:
  - Nightgunner5
  - 7031

database: true

description: 'This entire concept is totally logical. There is nothing more logical than being killed by absolutely everything at the same time. Plus, you get bonus points for not dying.'

main: com.stuzzhosting.totallylogical.Main
load: startup